// Code generated by microgen 0.9.1. DO NOT EDIT.

package transport

import (
	"context"
	models "github.com/rituraj-junglee/container-critic/models"
)

func (set EndpointsSet) TrivyTrigger(arg0 context.Context, arg1 models.TriggerRequest) (res0 error) {
	request := TrivyTriggerRequest{TriggerReq: arg1}
	_, res0 = set.TrivyTriggerEndpoint(arg0, &request)
	if res0 != nil {
		return
	}
	return res0
}
