// Code generated by microgen 0.9.1. DO NOT EDIT.

package transport

import endpoint "github.com/go-kit/kit/endpoint"

// EndpointsSet implements Service API and used for transport purposes.
type EndpointsSet struct {
	TrivyTriggerEndpoint endpoint.Endpoint
}
