// Code generated by microgen 0.9.1. DO NOT EDIT.

package transport

import models "github.com/rituraj-junglee/container-critic/models"

type (
	TrivyTriggerRequest struct {
		TriggerReq models.TriggerRequest `json:"trigger_req"`
	}
	// Formal exchange type, please do not delete.
	TrivyTriggerResponse struct{}
)
