// Code generated by microgen 0.9.1. DO NOT EDIT.

package transport

import (
	"context"
	endpoint "github.com/go-kit/kit/endpoint"
	trigger "github.com/rituraj-junglee/container-critic/services/trigger"
)

func Endpoints(svc trigger.Service) EndpointsSet {
	return EndpointsSet{TrivyTriggerEndpoint: TrivyTriggerEndpoint(svc)}
}

func TrivyTriggerEndpoint(svc trigger.Service) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*TrivyTriggerRequest)
		res0 := svc.TrivyTrigger(arg0, req.TriggerReq)
		return &TrivyTriggerResponse{}, res0
	}
}
