// Code generated by microgen 0.9.1. DO NOT EDIT.

package transporthttp

import (
	httpkit "github.com/go-kit/kit/transport/http"
	transport "github.com/rituraj-junglee/container-critic/services/trigger/transport"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{TrivyTriggerEndpoint: httpkit.NewClient(
		"POST", u,
		_Encode_TrivyTrigger_Request,
		_Decode_TrivyTrigger_Response,
		opts...,
	).Endpoint()}
}
