// Code generated by microgen 0.9.1. DO NOT EDIT.

package transporthttp

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	transport "github.com/rituraj-junglee/container-critic/services/trigger/transport"
	http1 "net/http"
)

func NewHTTPHandler(endpoints *transport.EndpointsSet, opts ...http.ServerOption) http1.Handler {
	mux := mux.NewRouter()
	mux.Methods("POST").Path("/slack/trigger/trivy").Handler(
		http.NewServer(
			endpoints.TrivyTriggerEndpoint,
			_Decode_TrivyTrigger_Request,
			_Encode_TrivyTrigger_Response,
			opts...))
	return mux
}
